### ISSUE TITLE
Tracking causes Tidy 5e NPC sheets not to open

### ISSUE THREAD

**Issue by Janner3D** [crash1115/5e-training#104]
![image](https://github.com/crash1115/5e-training/assets/35965176/4e3c8867-efa7-4e75-958b-9920a66f52bc)
 
When I attempt to open NPC sheets that use kgar's Tidy 5e Sheet (v0.11.2), they refuse to do so, and I get the above error. Disabling Crash's Tracking & Training allows me to reopen those types of sheets.

**Comment by crash1115** [comment]
Should be fixed in version 1.0.4!
