### ISSUE TITLE
short description of task

### ISSUE THREAD

**Issue by Bogus73** [crash1115/5e-training#18]
Hi again.
I had one more idea for the tracker. 
cozuld you add the option to give a short description of the task, e.g. "Studying Deep Speech at Hogwarts University" You need 6 weeks to finish your training with a tutor and 8 hours of studying every day.

When you klick the name of the task the description would show for the player and when the die icon is pressed it would add a success.

Thank you.

**Comment by crash1115** [comment]
Yep, can do! Will make sure it gets into this coming weekend's release
