### ISSUE TITLE
Add cost to downtime activities

### ISSUE THREAD

**Issue by Handyfon** [crash1115/5e-training#27]
![image](https://user-images.githubusercontent.com/28778881/92910247-2a135280-f428-11ea-9bc6-ee351c30177d.png)
Please add the option to define costs per roll (maybe even with automatic deduction)

**Comment by crash1115** [comment]
Ooh, this is cool. I'll have it out with 0.5.0. I can see a use case for non-monetary costs for certain things, so automatic deductions might a no-go for the first iteration of the feature, but I'll see what I can do down the line!

**Comment by Handyfon** [comment]
Thanks a lot :D

Just as an idea, you could add a checkbox for "automatic deduction" that would probably be the easiest way ^^

**Comment by crash1115** [comment]
Just a quick update on this. It's slated for v.0.5.0 or sometime shortly after. My main focus with the changes of this update is extensibility - I want to give users the tools to make the module work for them. This means that as far as feature requests like this one go, I'm asking myself if it should be part of the core functionality of the module, or if it's a more specific use-case. Cost/auto-deduction is a really specific use case, but I can go general with this... 

Currently I'm looking at giving users the option to add some customizable extra fields to activities - this could be cost, time spent, and any number of other things - and then giving them the tools they need (hooks, an accessible API, etc) to make them do what they want to with those fields. 

It's something I'm still thinking about how to best implement, so I'm not entirely certain _all_ of this will make it into 0.5.0. At the very least the groundwork will be laid at that point. Just wanted to let you know I haven't forgotten about this, and that it is in the works (though maybe in a slightly different way than was originally imagined).

**Comment by crash1115** [comment]
As of 0.5.0, you can set up activities to run macros. These can be used to implement a cost and about a billion other cool things!

If you need help with a macro, feel free to tag me on Discord and I'll help you out. Otherwise there's some simple API docs at the bottom of the readme, and an example of a simple macro [here](https://github.com/crash1115/5e-training/blob/master/examples.md#increase-by-1d20-macro)
