### ISSUE TITLE
0.4.6 conflict with Ethck's Downtime tracking 

### ISSUE THREAD

**Issue by marman6** [crash1115/5e-training#33]
Just updated to the newest version from today and Ethck's section no longer shows under Downtime. If I disable this module it shows up correctly. Both showed before update

**Comment by crash1115** [comment]
Thanks for the report, looking into it now.

What version of dnd5e and Foundry are you running?

**Comment by marman6** [comment]
Not problem anything to help and Version 0.6.6 for Foundry, dnd5e is 0.96

**Comment by crash1115** [comment]
Temporary workaround while we're working on this... You can untick this setting in Ethck's mod to get both tabs to appear:

![image](https://user-images.githubusercontent.com/41387713/95402293-52825580-08dd-11eb-8f6e-064b774ea804.png)

**Comment by crash1115** [comment]
Version 0.4.7 has my half of a fix in it. I would imagine Ethck will have his part fixed very shortly, so keep an eye out.

**Comment by Ethck** [comment]
Version 0.2.6 of Ethck's Downtime Tracking fixes this bug, and feel free to verify.
