### ISSUE TITLE
Compatibility with Dice Tooltip.

### ISSUE THREAD

**Issue by Nova-Katt** [crash1115/5e-training#35]
Having this mod activated together with Dice Tooltip will still work, but when you put your mouse on the activity name, or the dice icon, you'll get errors in the console, because it seems to think that it's a weapon or something.
With the error coming up by hovering over both the icon and the name, the console quickly gets littered with errors.
Here is the error I'm getting.

> dicetooltip.js:171 Uncaught TypeError: Cannot read property 'hasAttack' of null
>     at checkItemTooltip (dicetooltip.js:171)
>     at HTMLDivElement.mouseenter (dicetooltip.js:54)
>     at HTMLDivElement.handle (jquery.min.js:2)
>     at HTMLDivElement.dispatch (jquery.min.js:2)
>     at HTMLDivElement.v.handle (jquery.min.js:2)

So it might be an idea to check that up. :)

Other than that, thanks for a nice, practical and very helpful module! :)

**Comment by crash1115** [comment]
Hey thanks for the report! I'm currently in the process of basically re-writing the module from scratch so I don't have a timeline for if/when a fix might be pushed out for this. It may be a matter of having support for this mod built into Dice Tooltip rather than the other way around, but I'll keep this in mind as I'm working and see what can be done!

**Comment by Nova-Katt** [comment]
Cool! As long as you're not stressing yourself out for it. :)

**Comment by crash1115** [comment]
Soooo I'm pretty sure that the issue causing the console error spam was resolved a while ago completely by accident. I haven't actually verified this, but I do know for a fact that it doesn't spew errors all over the place as of the upcoming release (0.6.0).

As far as true compatibility, it doesn't look like that's going to be technically feasible. I could probably add an option in this module to display similar tooltips, though, if people are interested in that.
