### ISSUE TITLE
Remove roll button from completed tasks

### ISSUE THREAD

**Issue by ccjmk** [crash1115/5e-training#38]
Currently, when a task is complete, if the player keeps on clicking to progress on it, the Completed chat message keeps on popping up. Hopefully the button can be removed, so that becomes a no-issue

**Comment by ccjmk** [comment]
(btw, i don't know how to add the Feature Request label to this, it's probably on your side)

**Comment by crash1115** [comment]
Hey thanks for the feedback! I'll add it to the list for the next big release! :)
