### ISSUE TITLE
Tidy 5e Sheet - New UI issues

### ISSUE THREAD

**Issue by megahead11** [crash1115/5e-training#40]
Due to the recent CSS overhaul of Tidy5e, it looks like it's no longer compatible with this module. The UI changes so now can't add new downtimes or edit existing ones. 
![image](https://user-images.githubusercontent.com/21242682/103491822-9ea93d00-4ddb-11eb-8bfa-d42c854b7d61.png)

**Comment by crash1115** [comment]
Working on a fix currently, should have it released soonish. Thanks for the report!
