### ISSUE TITLE
Can't push a branch on repository

### ISSUE THREAD

**Issue by hakimassouane** [crash1115/5e-training#42]
Hi not really sure how this works but I made a french translation file on another branch in local and would wish to push it and make a pull request but cannot do

`remote: Permission to crash1115/5e-training.git denied to hakimassouane.
fatal: unable to access 'https://github.com/crash1115/5e-training.git/': The requested URL returned error: 403
`

**Comment by crash1115** [comment]
Hi there! Correct procedure would be to fork this repo, push your changes to your fork (which you own), and then do a PR to merge it into the dev branch of this repo.

Could also just drop the contents of the json file in here and I'll make sure it gets added in the next patch.
