### ISSUE TITLE
Allow setting a pre-defined Bonus for rolls

### ISSUE THREAD

**Issue by GuiSim** [crash1115/5e-training#45]
Hello! I love this extension!

Would it be possible to have support for pre-defined bonuses to rolls? For example, a Mark of Healing Halfling should get +1d4 to all Herbalism Kit ability check. I'd like to set that once somewhere and not have my player require to enter "+1d4" every time they want to try to craft a potion.

I tried to see if there was a way to configure this in Foundry VTT DND 5e but it's not well supported.
I looked at Macros, DAE and Midi but there was no simple way to do this.

I'm open to suggestions, but a simple way to set a "This downtime activity always has a+1d4 bonus to all rolls" would solve my problem.

Let me know what you think!

**Comment by GuiSim** [comment]
Perhaps having the ability to bind a roll to a macro would help solve my problem here 🤔

**Comment by crash1115** [comment]
Hey there! Thanks for the suggestion!

Having an activity roll a macro is definitely something I've been considering for the next major release (looking like sometime after Foundry core 0.8.x). At the very least, that release will have some sort of foundation in place that allows that, though I'm not certain whether or not it'll make the cut for implementation.

Allowing for the input of custom rolls definitely will make the cut, though. That should allow you to do something along the lines of `1d20 + @abilities.dex.mod + @prof + 1d4` if you wanted to do something like "Roll a Dexterity(Acrobatics) check and add a d4" if they're proficient in Acrobatics.

**Comment by GuiSim** [comment]
Amazing!
To be sure I understood: would that be set up once per Downtime Activity?

Today you can already add a bonus dice in the default Foundry dice roll prompt, but I'd to set it once and not have to think about it.

Thanks Crash!

**Comment by crash1115** [comment]
That's correct. Presently when you create an activity, you have the option to do a Simple progression, a Skill/Tool/Ability check progression, and then a Skill/Tool/Ability with a DC. This would add a 4th(and 5th) 'Custom Formula' (and 'Custom Formula with DC') type, that would just have you enter what you want to roll when you create it.

"Rolling" the activity would skip the normal roll dialog that comes up (since that's baked into 5e's rolling system and doing a custom formula bypasses that), make the roll you put in that box, and add progress as normal, depending on whether or not you set a DC.

**Comment by crash1115** [comment]
I suppose the downside of that approach is that skipping the roll dialog is somewhat limiting. You can't roll advantage or disadvantage that way...

I'll think on it. I can see enough of a use case for an always present bonus to be applied to a roll outside of custom formulas, so I may just add a bonus field to the other types anyway.

**Comment by crash1115** [comment]
Okay, as of 0.5.0, you can use macros for this. Check out [this](https://github.com/crash1115/5e-training/blob/master/examples.md#increase-by-1d20-macro) section of the examples doc to see how you could implement a simple roll, and then just tweak it from there.

**Comment by GuiSim** [comment]
Love the Macro solution. Thanks for the stellar module!
