### ISSUE TITLE
Betterrollsfor5e compatibility

### ISSUE THREAD

**Issue by Ikabodo** [crash1115/5e-training#48]
Would be super nice if this module could detect betterrollsfor5e and use those instead of "normal" rolls for skills.

https://github.com/Ethck/Ethck-s-Downtime-Tracking/issues/51#issuecomment-784391923 Ethk did something similar in his mod.

**Comment by Ikabodo** [comment]
![image](https://user-images.githubusercontent.com/7766890/108815907-8244a800-75b5-11eb-879c-c2f1a032666c.png)
Without vs With Betterrollsfor5e

**Comment by crash1115** [comment]
Hey thanks for this request! Always appreciate it when people take the time to give suggestions.

Question - what features of BR are you hoping to have here? Matching roll card styles, or the entire overhaul of the way rolls function (with modifier hotkeys, support for dual rolls, etc), something else?

To be quite honest, I've got very little interest in building full support in for alternative roll modules; doing so slaps an additional layer of complexity onto something where I personally don't feel the benefits outweigh the downsides (increased likelihood of something breaking).

On the flip side, if all you're after is cards that match the BR ones for the sake of consistency, that's something I might be willing to consider. I use BR myself and sometimes my players nitpick that, lol.

**Comment by Ikabodo** [comment]
Ofcourse, the card style matching is kinda a pet peeve really. :) And I understand you not wanting to build in support for all the rolling options. The cards sorta solves most of it anyway, since you nowadays can roll for adv/disv afterwards for example.

My suggestion is that you simply use the betterrolls functions as an option the player can check for, if they want. It's mostly about changing one roll to another. That is, if you feel it's something you want!

Anyway, great module! Thanks for the hard work!

**Comment by Ikabodo** [comment]
There were some changes to betterrolls5e recently, that supposedly make integration easier. Maybe something to look into?

**Comment by crash1115** [comment]
As it stands presently, there's already a way within this module to use most of Better Rolls' functionality (the only complication would be getting those after-roll adv/disadv toggles to work) - it just comes with the provision that you have to use macro activities to do it, and therefore requires a little bit of coding know-how. If you want, I can hook you up with a sample macro that'll show you how to do that, but I'm afraid that my stance on support for other roll mods remains unchanged.

There MIGHT be a time down the line where I change my mind - sometime after rolls are reworked again in core and I have time to sit down and rebuild this mod from scratch with all the lessons learned from close to a year of developing mods for Foundry - but I'm not sure when that'll be at this point.
