### ISSUE TITLE
Downtime / Training tab doesn't show up on sheets

### ISSUE THREAD

**Issue by Aritei** [crash1115/5e-training#51]
As of 01.05.2021 I noticed that the downtime activity tab was suddenly gone. It just doesn't show anymore, no matter what I do.

This was also tested with a fresh world and no other modules activated.

**Comment by crash1115** [comment]
Hi there, thanks for the report! What versions of Foundry, dnd 5e, and the module are you running?

**Comment by Aritei** [comment]
Foundry on the current stable release (0.7.9), D&D 5e on system version 1.2.3 (current stable version from 3 months ago) and your mod on version 0.5.0 which is also the current one.

Just to be thorough, I also uninstalled and re-installed Foundry. Doesn't change a thing.

**Comment by crash1115** [comment]
Troubleshooted via discord. Seemed like module settings weren't being registered post downgrade. Issue resolved by uninstalling and reinstalling the module.
