### ISSUE TITLE
Missing buttons

### ISSUE THREAD

**Issue by Luthervian** [crash1115/5e-training#54]
Hello, I am using this with 7.10.

I don't have the buttons (to make categories, export, import, etc). Is there compatibility issues with other modules or a setting i may be missing? I really am interested in using this!

**Comment by Luthervian** [comment]
I started a second world, no modules active but this one, 7.10 Foundry VTT and still no buttons or way to create categories. It isn't a compatibility issue with other modules so it must be something I'm missing, doing wrong, or an issue with 7.10

**Comment by crash1115** [comment]
Hello there! Not a bug, and you're not doing anything wrong. Just version compatibility issues. The version of TNT that implements categories and import/export (v0.6.0) is only compatible with Foundry 0.8.x. You're probably running TNT 0.5.0.

At this point in time I don't have any plans to back-port the changes to the latest version so they can work with 0.7.x, so if you want to use the new stuff, you'll need to be on Foundry 0.8.x. I wouldn't recommend making that switch just for this module, though.

**Comment by Luthervian** [comment]
Thanks for the reply. Good to know. I'll be doing the update to 0.8.x
tomorrow... so very glad to hear this!

**Comment by crash1115** [comment]
All the new stuff in 0.8.x is pretty awesome, so have fun! (And don't forget to back up all your user data before you make the switch!)
