### ISSUE TITLE
Bug report regarding Importing and Suggestion

### ISSUE THREAD

**Issue by turboraton** [crash1115/5e-training#65]
Hey there Crash, first of all let me thank you for your WONDERFUL module! 

First of all I wanted to report a bug: when you import, the categories don't remain and it puts them all into uncategorized 
![image](https://user-images.githubusercontent.com/70917100/127782002-bc5f6513-9916-41ee-9e26-03b5c0411da7.png)

Lastly. As you can see I'm using your amazing module to track reputation for my players and the different factions they encounter. I was wondering that if you could include a threshold mechanic where for example, if it reaches a % of the progress, something happens (just a text display or a change of colour of the progress bar is more than enough for me).

Many thanks again and have a good day!

**Comment by crash1115** [comment]
Hey, thanks for getting in touch, and glad you're enjoying the module!

The issue with categories not importing isn't a bug; it's working as intended. At present, categories are unique to the actor they're created on and don't get sent along when tracked items get exported. The good news is that it's probably fairly easy for me to fix (though I don't have a timeline for you on that). You can find the ticket for that here: https://github.com/crash1115/5e-training/issues/64

As far as progress thresholds doing things, what are you trying to accomplish with such a feature? Depending on what your use case is, I can recommend a few different options that you can use to get the desired outcome using what's already available in the module.

**Comment by turboraton** [comment]
Hello there, sorry for the late reply. Currently I'm using your great system in order to track reputation with the factions as you can see. I was thinking the following:

- First, it would be neat if different colors could be shown on the progress bar according to the progress. That way it could be green or gold if you are in the highest standing with that faction and bright red or black if you are at the lowest.
- Secondly I was thinking that perhaps you could add a threshold system and that could also work for your tracking and training. For example, if you are at 40%, a text could show that says "unfriendly" while at 80% the text would display "exalted". 

Thanks again for your great module!

**Comment by crash1115** [comment]
Okay, that's definitely possible to do currently with a world script or something similar, but probably outside of the realms of something simple enough I could show you how to do. (If I have some free time this weekend I might see what I can slap together for you, but no promises.)

As far as a feature request, I'm on the fence about it. One of my goals with this module was to keep every feature general enough that anyone using it could use it for pretty much anything they wanted. Your use case there is pretty specific to reputation, and while that's not an uncommon use case by any stretch, it's cutting awfully close to being too specific.

That's not a flat out "no thanks" by any means; I just need to give it a think and see if there's a way I could implement something like that in a more generally applicable way that isn't going to be a) cumbersome or b) largely ignored by anyone not doing something like reputation with it. Thanks for the suggestion!

**Comment by turboraton** [comment]
Thanks for your reply! This could also be implemented for training and
tracking as a partial threshold for bonuses. Imagine you are training a new
skill and a partial threshold could give you the proficiency while a total
could give you the expertise. But yeah, it would be mostly used for
tracking fame and benefits from a patron or faction.

**Comment by crash1115** [comment]
Just wanted to say, categories now import properly as of v1.0.0. The rest of the stuff in here won't be worked on, as I'm not gonna be continuing actively developing the module.
