### ISSUE TITLE
["Bug"] Ampersand in module name isn't rendered properly

### ISSUE THREAD

**Issue by tagnullde** [crash1115/5e-training#67]
A screenshot says more than a thousand words. ;)

![image](https://user-images.githubusercontent.com/44159008/131003682-500fa89a-f9fe-4986-b38b-0159684de983.png)

**Comment by crash1115** [comment]
Hey thanks for the report! This is a known Foundry core issue. Seems like it's being worked on for v9. https://gitlab.com/foundrynet/foundryvtt/-/issues/5738

I'll leave this open until it gets fixed just for visibility's sake, but I am gonna tag it as `wontfix` on my end.

**Comment by tagnullde** [comment]
That's fair. Didn't know it's a core thing.

**Comment by crash1115** [comment]
Closing, this got fixed somewhere in Foundry v9.
