### ISSUE TITLE
Armor Class calculation error.

### ISSUE THREAD

**Issue by Forget779** [crash1115/5e-training#73]
I have a barbarian in my party as I was creating their character using this module and the armor class formula for unarmored defense via barbarian, the AC remained the default ten on the sheet. The attached image shows the character sheet of the half-orc barbarian, and the problematic calculation display.
![OGL_CS_Error](https://user-images.githubusercontent.com/92732409/139078605-0e8d2f97-6ff2-44fd-ad85-fd51c34d5aad.png)

**Comment by Forget779** [comment]
As you can see the proper math displays on the configuration settings but not on the character sheet itself. Additionally, it would only update the AC without armor if and only if the dexterity mod is greater than or less than 0 not effected by the constitution score.

**Comment by crash1115** [comment]
Hey there, thanks for the report!

Seems like you've got a module installed that's adjusting the style of the character sheet - does this issue still occur if you set the sheet to use the vanilla dnd5e character sheet?

**Comment by Forget779** [comment]
I will attempt this tomorrow. To try and assess the difference I am using
the OGL character sheet module where the glitch is occurring initially. I
will double check soon.

**Comment by crash1115** [comment]
Sounds good, thanks. I'm just trying to narrow down if this is an issue with the sheet module or not; mine doesn't really touch anything that should mess with the AC calculation, so knowing if it's sheet specific can help me narrow down what the issue might be.

**Comment by Forget779** [comment]
Unfortunately, I have tried it with the vanilla and the OGL module. The
obsidian module allows the DM to adjust the armor class manually but not by
a preset feature. I prefer the OGL module sheet because I can have the
party track the quests they take. However, this module is very useful.

**Comment by crash1115** [comment]
Interesting. I can't seem to reproduce this issue, so it might be another module conflict, something strange with the particular actor, or something I'm just missing entirely. Couple more questions:

1. What versions of foundry and dnd5e are you running?

2. If you open the character sheet then open the console (F12 for windows > console tab), do you see any errors (red text)?

3. Can you export the actor you're having trouble with (right click it in the actors sidebar > export) and attach it to a comment in this thread? You'll probably have to put the json file into a zip folder, then drag/drop that into a reply. Should do the trick.

Thanks!

**Comment by Forget779** [comment]
Will do. I’ll have that into you soon.
