### ISSUE TITLE
Add visibility toggles to individual tracked items

### ISSUE THREAD

**Issue by crash1115** [crash1115/5e-training#74]
Add the ability to control visibility on a per-item basis. Maybe a checkbox that says "GM Only"

Requested by KingRavos#1337 here: https://discord.com/channels/170995199584108546/513918036919713802/908134288279634011

**Comment by DeimosJ** [comment]
To add to this feature perhaps include the option to create a GM editable only option, so the tracked item remains visible to the player but can only be updated by the GM (or perhaps an assistant user?).
This could be added as a permissions drop down together with the above visibility option perhaps?
