### ISSUE TITLE
[Feature request] Tie into character sheet rolls

### ISSUE THREAD

**Issue by Orionox** [crash1115/5e-training#81]
would be super cool if you could tie the tracker to anytime you rolled a specific skill. So like anytime i rolled a med skill check it would increase the tracker.

**Comment by crash1115** [comment]
Hey thanks for the request! This is probably possible, but it's not something I'm interested in developing as a feature at this time. Different modules that change how rolling works make it somewhat more of a pain in the butt than I'd like to make sure most things are compatible.
