### ISSUE TITLE
midi-qol oddities

### ISSUE THREAD

**Issue by tposney** [crash1115/5e-training#83]
As of v 0.9.26 midi will properly respect the options.vanilla flag in ability checks/skill/saves rolls so the special case for midi and better rolls in your options won't be required.
I'd suggest changing 
```js
if (!game.modules.get("midi-qol")?.active){ options.vanilla = true; }; //Handles BR. Want it on in all cases except when midi is enabled
```
to 
```js
if (!game.modules.get("midi-qol")?.active || isNewerVersion(game.modules.get("midi-qol").data.version, "0.9.25")) {options.vanilla = true}
```
which works as expected in my testing

**Comment by crash1115** [comment]
Thanks, Tim! Fixed in v0.6.9.
