### ISSUE TITLE
Compendium options?

### ISSUE THREAD

**Issue by AdvTimber** [crash1115/5e-training#89]
I'm currently transcribing Kibbles Crafting Compendium into my Foundry game. Your import guide says it's meant for backup/troubleshooting.

Would it be best to create each entry, export them, and then import them to other characters?

Is there a way to copy the entries to a compendium folder and then drag and drop them like features/items into another character?

**Comment by crash1115** [comment]
Hey there!

> Is there a way to copy the entries to a compendium folder

Nope.

> Would it be best to create each entry, export them, and then import them to other characters?

This is probably the route I'd take if I were doing this, but there are some gotchas. Presently import/export doesn't support categories, so if you have them broken up like that, they're probably not going to import as expected. It's just something I haven't had time to fix.

**Comment by AdvTimber** [comment]
Okie. No problem.

**Comment by crash1115** [comment]
Hey just wanted to provide a quick update here!

> Would it be best to create each entry, export them, and then import them to other characters?

This use case is now supported, as categories will now import/export along with tracked items as of v1.0.0. Happy crafting!
