### ISSUE TITLE
Incompatibility with Compact DnDBeyond-like 5e Character Sheet

### ISSUE THREAD

**Issue by dmr612** [crash1115/5e-training#96]
Tracking interface won't load while using Compact DnDBeyond-like 5e Character Sheet, instead interface shows the bio

**Comment by crash1115** [comment]
Should be working as of dnd 2.4.1 and downtime v1.0.3.
![image](https://github.com/crash1115/5e-training/assets/41387713/d03dc802-4868-48b4-b6ce-5623cf7507aa)
