### ISSUE TITLE
The downtime tab is inconsistent in compendiums

### ISSUE THREAD

**Issue by TheAlexPlus** [crash1115/5e-training#99]
I'm currently preparing for a campaign and creating all the NPCs.  I wanted to use this to track loyalty scores, but when i went into the compendium to edit the actors, the downtime tab doesn't show up.
BUT THEN, I randomly discovered that SOME show the downtime tab, but some don't and I have no idea what's causing this.

Even if i import an actor into the world so the tab shows up, edit it, then put it back in the compendium, the tab is still gone.
The actor that HAS the downtime tab hasn't been edited at all since putting it in the compendium and activating the module.

I'm on V10.303
Dnd5e V 2.3.1

**Comment by crash1115** [comment]
Hello!

It's intended that the tab won't display when opening an actor from a compendium. If you need to update downtime data for an actor in a compendium, import the actor first, open their sheet from the Actors tab, make any adjustments you need, and then stick them back into the compendium. The downtime data should be retained for the next time they're imported into the world. (If the tab isn't showing up when they're opened from the Actors tab, then check the module settings. There's a toggle in there for which types of actors the tab should display on - NPCs, PCs, or both. If that setting is set correctly, and you're still experiencing issues seeing the tab, then something is up.)

At this point I'm not maintaining this module anymore, and don't really have time to be fixing issues or taking feature requests. If the tab not displaying when opening an actor from a compendium is make or break for you, I'd suggest you check out [Downtime Dnd5e](https://github.com/p4535992/foundryvtt-downtime-dnd5e) (which is a sort of successor to this module) and make those bug reports or feature requests over there if they're still issues in that version of the mod.
